language: python
python:
  - "3.4"
install:
  - "pip install -r requirements/travis.txt"
script:
  - "cp etc/local_config.yaml.sample local_config.yaml"
  - "sed -i 's/secret_key:.*/secret_key: classified_secret_key/g' local_config.yaml"
  - "sed -i 's/db_host:.*/db_host: localhost/g' local_config.yaml"
  - "sed -i 's/db_port:.*/db_port: 5432/g' local_config.yaml"
  - "sed -i 's/db_name:.*/db_name: volontulo/g' local_config.yaml"
  - "sed -i 's/db_user:.*/db_user: postgres/g' local_config.yaml"
  - "sed -i 's/db_pass:.*/db_pass:/g' local_config.yaml"
  - "pep8 --exclude='apps/volontulo/migrations/*,node_modules,.ropeproject' ."
  - "pylint --load-plugins pylint_django --min-similarity-lines=10 apps"
  - "coverage run --source='./apps' manage.py test --settings=volontulo_org.settings.test_settings -v 3"
  - "cd apps/volontulo && npm install && gulp build && cd ../.."
after_success:
  - "codecov"
